// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: recognition.proto

package recognition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecognitionService_HealthCheck_FullMethodName                = "/recognition.RecognitionService/HealthCheck"
	RecognitionService_Ping_FullMethodName                       = "/recognition.RecognitionService/Ping"
	RecognitionService_TestRecognize_FullMethodName              = "/recognition.RecognitionService/TestRecognize"
	RecognitionService_TestRecognizeVideo_FullMethodName         = "/recognition.RecognitionService/TestRecognizeVideo"
	RecognitionService_RecognizeFromStream_FullMethodName        = "/recognition.RecognitionService/RecognizeFromStream"
	RecognitionService_StopStreamRecognition_FullMethodName      = "/recognition.RecognitionService/StopStreamRecognition"
	RecognitionService_GetStreamRecognitionStatus_FullMethodName = "/recognition.RecognitionService/GetStreamRecognitionStatus"
	RecognitionService_StartWorker_FullMethodName                = "/recognition.RecognitionService/StartWorker"
	RecognitionService_StopWorker_FullMethodName                 = "/recognition.RecognitionService/StopWorker"
	RecognitionService_GetWorkerStatus_FullMethodName            = "/recognition.RecognitionService/GetWorkerStatus"
)

// RecognitionServiceClient is the client API for RecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecognitionService provides automatic number plate recognition functionality
type RecognitionServiceClient interface {
	// Test methods
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	TestRecognize(ctx context.Context, in *TestRecognizeRequest, opts ...grpc.CallOption) (*TestRecognizeResponse, error)
	TestRecognizeVideo(ctx context.Context, in *TestVideoRequest, opts ...grpc.CallOption) (*TestVideoResponse, error)
	// Production methods
	RecognizeFromStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	StopStreamRecognition(ctx context.Context, in *StopStreamRecognitionRequest, opts ...grpc.CallOption) (*StopStreamRecognitionResponse, error)
	GetStreamRecognitionStatus(ctx context.Context, in *StreamRecognitionStatusRequest, opts ...grpc.CallOption) (*StreamRecognitionStatusResponse, error)
	// Worker management
	StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*StartWorkerResponse, error)
	StopWorker(ctx context.Context, in *StopWorkerRequest, opts ...grpc.CallOption) (*StopWorkerResponse, error)
	GetWorkerStatus(ctx context.Context, in *GetWorkerStatusRequest, opts ...grpc.CallOption) (*GetWorkerStatusResponse, error)
}

type recognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognitionServiceClient(cc grpc.ClientConnInterface) RecognitionServiceClient {
	return &recognitionServiceClient{cc}
}

func (c *recognitionServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RecognitionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RecognitionService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) TestRecognize(ctx context.Context, in *TestRecognizeRequest, opts ...grpc.CallOption) (*TestRecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRecognizeResponse)
	err := c.cc.Invoke(ctx, RecognitionService_TestRecognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) TestRecognizeVideo(ctx context.Context, in *TestVideoRequest, opts ...grpc.CallOption) (*TestVideoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestVideoResponse)
	err := c.cc.Invoke(ctx, RecognitionService_TestRecognizeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) RecognizeFromStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, RecognitionService_RecognizeFromStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) StopStreamRecognition(ctx context.Context, in *StopStreamRecognitionRequest, opts ...grpc.CallOption) (*StopStreamRecognitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopStreamRecognitionResponse)
	err := c.cc.Invoke(ctx, RecognitionService_StopStreamRecognition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) GetStreamRecognitionStatus(ctx context.Context, in *StreamRecognitionStatusRequest, opts ...grpc.CallOption) (*StreamRecognitionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamRecognitionStatusResponse)
	err := c.cc.Invoke(ctx, RecognitionService_GetStreamRecognitionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) StartWorker(ctx context.Context, in *StartWorkerRequest, opts ...grpc.CallOption) (*StartWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkerResponse)
	err := c.cc.Invoke(ctx, RecognitionService_StartWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) StopWorker(ctx context.Context, in *StopWorkerRequest, opts ...grpc.CallOption) (*StopWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopWorkerResponse)
	err := c.cc.Invoke(ctx, RecognitionService_StopWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) GetWorkerStatus(ctx context.Context, in *GetWorkerStatusRequest, opts ...grpc.CallOption) (*GetWorkerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkerStatusResponse)
	err := c.cc.Invoke(ctx, RecognitionService_GetWorkerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecognitionServiceServer is the server API for RecognitionService service.
// All implementations must embed UnimplementedRecognitionServiceServer
// for forward compatibility.
//
// RecognitionService provides automatic number plate recognition functionality
type RecognitionServiceServer interface {
	// Test methods
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	TestRecognize(context.Context, *TestRecognizeRequest) (*TestRecognizeResponse, error)
	TestRecognizeVideo(context.Context, *TestVideoRequest) (*TestVideoResponse, error)
	// Production methods
	RecognizeFromStream(context.Context, *StreamRequest) (*RecognizeResponse, error)
	StopStreamRecognition(context.Context, *StopStreamRecognitionRequest) (*StopStreamRecognitionResponse, error)
	GetStreamRecognitionStatus(context.Context, *StreamRecognitionStatusRequest) (*StreamRecognitionStatusResponse, error)
	// Worker management
	StartWorker(context.Context, *StartWorkerRequest) (*StartWorkerResponse, error)
	StopWorker(context.Context, *StopWorkerRequest) (*StopWorkerResponse, error)
	GetWorkerStatus(context.Context, *GetWorkerStatusRequest) (*GetWorkerStatusResponse, error)
	mustEmbedUnimplementedRecognitionServiceServer()
}

// UnimplementedRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognitionServiceServer struct{}

func (UnimplementedRecognitionServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRecognitionServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRecognitionServiceServer) TestRecognize(context.Context, *TestRecognizeRequest) (*TestRecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRecognize not implemented")
}
func (UnimplementedRecognitionServiceServer) TestRecognizeVideo(context.Context, *TestVideoRequest) (*TestVideoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRecognizeVideo not implemented")
}
func (UnimplementedRecognitionServiceServer) RecognizeFromStream(context.Context, *StreamRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeFromStream not implemented")
}
func (UnimplementedRecognitionServiceServer) StopStreamRecognition(context.Context, *StopStreamRecognitionRequest) (*StopStreamRecognitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStreamRecognition not implemented")
}
func (UnimplementedRecognitionServiceServer) GetStreamRecognitionStatus(context.Context, *StreamRecognitionStatusRequest) (*StreamRecognitionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamRecognitionStatus not implemented")
}
func (UnimplementedRecognitionServiceServer) StartWorker(context.Context, *StartWorkerRequest) (*StartWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorker not implemented")
}
func (UnimplementedRecognitionServiceServer) StopWorker(context.Context, *StopWorkerRequest) (*StopWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorker not implemented")
}
func (UnimplementedRecognitionServiceServer) GetWorkerStatus(context.Context, *GetWorkerStatusRequest) (*GetWorkerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerStatus not implemented")
}
func (UnimplementedRecognitionServiceServer) mustEmbedUnimplementedRecognitionServiceServer() {}
func (UnimplementedRecognitionServiceServer) testEmbeddedByValue()                            {}

// UnsafeRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognitionServiceServer will
// result in compilation errors.
type UnsafeRecognitionServiceServer interface {
	mustEmbedUnimplementedRecognitionServiceServer()
}

func RegisterRecognitionServiceServer(s grpc.ServiceRegistrar, srv RecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecognitionService_ServiceDesc, srv)
}

func _RecognitionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_TestRecognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).TestRecognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_TestRecognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).TestRecognize(ctx, req.(*TestRecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_TestRecognizeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).TestRecognizeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_TestRecognizeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).TestRecognizeVideo(ctx, req.(*TestVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_RecognizeFromStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).RecognizeFromStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_RecognizeFromStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).RecognizeFromStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_StopStreamRecognition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStreamRecognitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).StopStreamRecognition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_StopStreamRecognition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).StopStreamRecognition(ctx, req.(*StopStreamRecognitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_GetStreamRecognitionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRecognitionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).GetStreamRecognitionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_GetStreamRecognitionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).GetStreamRecognitionStatus(ctx, req.(*StreamRecognitionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_StartWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).StartWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_StartWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).StartWorker(ctx, req.(*StartWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_StopWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).StopWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_StopWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).StopWorker(ctx, req.(*StopWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_GetWorkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).GetWorkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_GetWorkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).GetWorkerStatus(ctx, req.(*GetWorkerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecognitionService_ServiceDesc is the grpc.ServiceDesc for RecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recognition.RecognitionService",
	HandlerType: (*RecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _RecognitionService_HealthCheck_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RecognitionService_Ping_Handler,
		},
		{
			MethodName: "TestRecognize",
			Handler:    _RecognitionService_TestRecognize_Handler,
		},
		{
			MethodName: "TestRecognizeVideo",
			Handler:    _RecognitionService_TestRecognizeVideo_Handler,
		},
		{
			MethodName: "RecognizeFromStream",
			Handler:    _RecognitionService_RecognizeFromStream_Handler,
		},
		{
			MethodName: "StopStreamRecognition",
			Handler:    _RecognitionService_StopStreamRecognition_Handler,
		},
		{
			MethodName: "GetStreamRecognitionStatus",
			Handler:    _RecognitionService_GetStreamRecognitionStatus_Handler,
		},
		{
			MethodName: "StartWorker",
			Handler:    _RecognitionService_StartWorker_Handler,
		},
		{
			MethodName: "StopWorker",
			Handler:    _RecognitionService_StopWorker_Handler,
		},
		{
			MethodName: "GetWorkerStatus",
			Handler:    _RecognitionService_GetWorkerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recognition.proto",
}
