// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: recognition.proto

package recognition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for requests without parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_recognition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{0}
}

// HealthResponse returns service health status
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_recognition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// PingRequest for testing connectivity
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_recognition_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResponse echoes back the message
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_recognition_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// TestRecognizeRequest for testing recognition without RTSP
type TestRecognizeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImageBase64    string                 `protobuf:"bytes,1,opt,name=image_base64,json=imageBase64,proto3" json:"image_base64,omitempty"`
	UseSampleImage bool                   `protobuf:"varint,2,opt,name=use_sample_image,json=useSampleImage,proto3" json:"use_sample_image,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestRecognizeRequest) Reset() {
	*x = TestRecognizeRequest{}
	mi := &file_recognition_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRecognizeRequest) ProtoMessage() {}

func (x *TestRecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRecognizeRequest.ProtoReflect.Descriptor instead.
func (*TestRecognizeRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{4}
}

func (x *TestRecognizeRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *TestRecognizeRequest) GetUseSampleImage() bool {
	if x != nil {
		return x.UseSampleImage
	}
	return false
}

// TestRecognizeResponse returns test recognition results
type TestRecognizeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Plates           []*PlateResult         `protobuf:"bytes,2,rep,name=plates,proto3" json:"plates,omitempty"`
	ProcessingTimeMs string                 `protobuf:"bytes,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	Error            string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TestRecognizeResponse) Reset() {
	*x = TestRecognizeResponse{}
	mi := &file_recognition_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRecognizeResponse) ProtoMessage() {}

func (x *TestRecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRecognizeResponse.ProtoReflect.Descriptor instead.
func (*TestRecognizeResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{5}
}

func (x *TestRecognizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestRecognizeResponse) GetPlates() []*PlateResult {
	if x != nil {
		return x.Plates
	}
	return nil
}

func (x *TestRecognizeResponse) GetProcessingTimeMs() string {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return ""
}

func (x *TestRecognizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PlateResult represents a single recognized plate
type PlateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateNumber   string                 `protobuf:"bytes,1,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	BoundingBox   *BoundingBox           `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlateResult) Reset() {
	*x = PlateResult{}
	mi := &file_recognition_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateResult) ProtoMessage() {}

func (x *PlateResult) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateResult.ProtoReflect.Descriptor instead.
func (*PlateResult) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{6}
}

func (x *PlateResult) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *PlateResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PlateResult) GetBoundingBox() *BoundingBox {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

// BoundingBox defines the location of detected plate
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_recognition_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{7}
}

func (x *BoundingBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// RTSPRequest to start RTSP stream recognition
type RTSPRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RtspUrl             string                 `protobuf:"bytes,2,opt,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`
	FrameInterval       int32                  `protobuf:"varint,3,opt,name=frame_interval,json=frameInterval,proto3" json:"frame_interval,omitempty"` // Process every Nth frame
	ConfidenceThreshold float64                `protobuf:"fixed64,4,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RTSPRequest) Reset() {
	*x = RTSPRequest{}
	mi := &file_recognition_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTSPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTSPRequest) ProtoMessage() {}

func (x *RTSPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTSPRequest.ProtoReflect.Descriptor instead.
func (*RTSPRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{8}
}

func (x *RTSPRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RTSPRequest) GetRtspUrl() string {
	if x != nil {
		return x.RtspUrl
	}
	return ""
}

func (x *RTSPRequest) GetFrameInterval() int32 {
	if x != nil {
		return x.FrameInterval
	}
	return 0
}

func (x *RTSPRequest) GetConfidenceThreshold() float64 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

// RecognizeResponse for RTSP recognition start
type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_recognition_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{9}
}

func (x *RecognizeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecognizeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecognizeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecognizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StopRTSPRequest to stop RTSP stream recognition
type StopRTSPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRTSPRequest) Reset() {
	*x = StopRTSPRequest{}
	mi := &file_recognition_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRTSPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRTSPRequest) ProtoMessage() {}

func (x *StopRTSPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRTSPRequest.ProtoReflect.Descriptor instead.
func (*StopRTSPRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{10}
}

func (x *StopRTSPRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// StopRTSPResponse confirms RTSP stop
type StopRTSPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRTSPResponse) Reset() {
	*x = StopRTSPResponse{}
	mi := &file_recognition_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRTSPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRTSPResponse) ProtoMessage() {}

func (x *StopRTSPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRTSPResponse.ProtoReflect.Descriptor instead.
func (*StopRTSPResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{11}
}

func (x *StopRTSPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRTSPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopRTSPResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RTSPStatusRequest to check RTSP stream status
type RTSPStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTSPStatusRequest) Reset() {
	*x = RTSPStatusRequest{}
	mi := &file_recognition_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTSPStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTSPStatusRequest) ProtoMessage() {}

func (x *RTSPStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTSPStatusRequest.ProtoReflect.Descriptor instead.
func (*RTSPStatusRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{12}
}

func (x *RTSPStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// RTSPStatusResponse returns RTSP stream status
type RTSPStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "error"
	FramesProcessed int64                  `protobuf:"varint,3,opt,name=frames_processed,json=framesProcessed,proto3" json:"frames_processed,omitempty"`
	PlatesDetected  int64                  `protobuf:"varint,4,opt,name=plates_detected,json=platesDetected,proto3" json:"plates_detected,omitempty"`
	StartedAt       string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RTSPStatusResponse) Reset() {
	*x = RTSPStatusResponse{}
	mi := &file_recognition_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTSPStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTSPStatusResponse) ProtoMessage() {}

func (x *RTSPStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTSPStatusResponse.ProtoReflect.Descriptor instead.
func (*RTSPStatusResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{13}
}

func (x *RTSPStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RTSPStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RTSPStatusResponse) GetFramesProcessed() int64 {
	if x != nil {
		return x.FramesProcessed
	}
	return 0
}

func (x *RTSPStatusResponse) GetPlatesDetected() int64 {
	if x != nil {
		return x.PlatesDetected
	}
	return 0
}

func (x *RTSPStatusResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RTSPStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Worker management messages
type StartWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	RtspUrl       string                 `protobuf:"bytes,2,opt,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkerRequest) Reset() {
	*x = StartWorkerRequest{}
	mi := &file_recognition_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkerRequest) ProtoMessage() {}

func (x *StartWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkerRequest.ProtoReflect.Descriptor instead.
func (*StartWorkerRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{14}
}

func (x *StartWorkerRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *StartWorkerRequest) GetRtspUrl() string {
	if x != nil {
		return x.RtspUrl
	}
	return ""
}

type StartWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkerResponse) Reset() {
	*x = StartWorkerResponse{}
	mi := &file_recognition_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkerResponse) ProtoMessage() {}

func (x *StartWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkerResponse.ProtoReflect.Descriptor instead.
func (*StartWorkerResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{15}
}

func (x *StartWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartWorkerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkerRequest) Reset() {
	*x = StopWorkerRequest{}
	mi := &file_recognition_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkerRequest) ProtoMessage() {}

func (x *StopWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkerRequest.ProtoReflect.Descriptor instead.
func (*StopWorkerRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{16}
}

func (x *StopWorkerRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type StopWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkerResponse) Reset() {
	*x = StopWorkerResponse{}
	mi := &file_recognition_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkerResponse) ProtoMessage() {}

func (x *StopWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkerResponse.ProtoReflect.Descriptor instead.
func (*StopWorkerResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{17}
}

func (x *StopWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopWorkerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetWorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerStatusRequest) Reset() {
	*x = GetWorkerStatusRequest{}
	mi := &file_recognition_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerStatusRequest) ProtoMessage() {}

func (x *GetWorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{18}
}

func (x *GetWorkerStatusRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

type GetWorkerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "error"
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerStatusResponse) Reset() {
	*x = GetWorkerStatusResponse{}
	mi := &file_recognition_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerStatusResponse) ProtoMessage() {}

func (x *GetWorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_recognition_proto_rawDescGZIP(), []int{19}
}

func (x *GetWorkerStatusResponse) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *GetWorkerStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkerStatusResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *GetWorkerStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_recognition_proto protoreflect.FileDescriptor

const file_recognition_proto_rawDesc = "" +
	"\n" +
	"\x11recognition.proto\x12\vrecognition\"\a\n" +
	"\x05Empty\"b\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"c\n" +
	"\x14TestRecognizeRequest\x12!\n" +
	"\fimage_base64\x18\x01 \x01(\tR\vimageBase64\x12(\n" +
	"\x10use_sample_image\x18\x02 \x01(\bR\x0euseSampleImage\"\xa7\x01\n" +
	"\x15TestRecognizeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x06plates\x18\x02 \x03(\v2\x18.recognition.PlateResultR\x06plates\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\tR\x10processingTimeMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8d\x01\n" +
	"\vPlateResult\x12!\n" +
	"\fplate_number\x18\x01 \x01(\tR\vplateNumber\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12;\n" +
	"\fbounding_box\x18\x03 \x01(\v2\x18.recognition.BoundingBoxR\vboundingBox\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xa1\x01\n" +
	"\vRTSPRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\brtsp_url\x18\x02 \x01(\tR\artspUrl\x12%\n" +
	"\x0eframe_interval\x18\x03 \x01(\x05R\rframeInterval\x121\n" +
	"\x14confidence_threshold\x18\x04 \x01(\x01R\x13confidenceThreshold\"|\n" +
	"\x11RecognizeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"0\n" +
	"\x0fStopRTSPRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\\\n" +
	"\x10StopRTSPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"2\n" +
	"\x11RTSPStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xd4\x01\n" +
	"\x12RTSPStatusResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10frames_processed\x18\x03 \x01(\x03R\x0fframesProcessed\x12'\n" +
	"\x0fplates_detected\x18\x04 \x01(\x03R\x0eplatesDetected\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"L\n" +
	"\x12StartWorkerRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x19\n" +
	"\brtsp_url\x18\x02 \x01(\tR\artspUrl\"_\n" +
	"\x13StartWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"0\n" +
	"\x11StopWorkerRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"^\n" +
	"\x12StopWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"5\n" +
	"\x16GetWorkerStatusRequest\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\"\x83\x01\n" +
	"\x17GetWorkerStatusResponse\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xdd\x05\n" +
	"\x12RecognitionService\x12>\n" +
	"\vHealthCheck\x12\x12.recognition.Empty\x1a\x1b.recognition.HealthResponse\x12;\n" +
	"\x04Ping\x12\x18.recognition.PingRequest\x1a\x19.recognition.PingResponse\x12V\n" +
	"\rTestRecognize\x12!.recognition.TestRecognizeRequest\x1a\".recognition.TestRecognizeResponse\x12M\n" +
	"\x11RecognizeFromRTSP\x12\x18.recognition.RTSPRequest\x1a\x1e.recognition.RecognizeResponse\x12R\n" +
	"\x13StopRTSPRecognition\x12\x1c.recognition.StopRTSPRequest\x1a\x1d.recognition.StopRTSPResponse\x12P\n" +
	"\rGetRTSPStatus\x12\x1e.recognition.RTSPStatusRequest\x1a\x1f.recognition.RTSPStatusResponse\x12P\n" +
	"\vStartWorker\x12\x1f.recognition.StartWorkerRequest\x1a .recognition.StartWorkerResponse\x12M\n" +
	"\n" +
	"StopWorker\x12\x1e.recognition.StopWorkerRequest\x1a\x1f.recognition.StopWorkerResponse\x12\\\n" +
	"\x0fGetWorkerStatus\x12#.recognition.GetWorkerStatusRequest\x1a$.recognition.GetWorkerStatusResponseBJZHgithub.com/VsRnA/Automatic-Number-Plate-Recognition/pkg/grpc/recognitionb\x06proto3"

var (
	file_recognition_proto_rawDescOnce sync.Once
	file_recognition_proto_rawDescData []byte
)

func file_recognition_proto_rawDescGZIP() []byte {
	file_recognition_proto_rawDescOnce.Do(func() {
		file_recognition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recognition_proto_rawDesc), len(file_recognition_proto_rawDesc)))
	})
	return file_recognition_proto_rawDescData
}

var file_recognition_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_recognition_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: recognition.Empty
	(*HealthResponse)(nil),          // 1: recognition.HealthResponse
	(*PingRequest)(nil),             // 2: recognition.PingRequest
	(*PingResponse)(nil),            // 3: recognition.PingResponse
	(*TestRecognizeRequest)(nil),    // 4: recognition.TestRecognizeRequest
	(*TestRecognizeResponse)(nil),   // 5: recognition.TestRecognizeResponse
	(*PlateResult)(nil),             // 6: recognition.PlateResult
	(*BoundingBox)(nil),             // 7: recognition.BoundingBox
	(*RTSPRequest)(nil),             // 8: recognition.RTSPRequest
	(*RecognizeResponse)(nil),       // 9: recognition.RecognizeResponse
	(*StopRTSPRequest)(nil),         // 10: recognition.StopRTSPRequest
	(*StopRTSPResponse)(nil),        // 11: recognition.StopRTSPResponse
	(*RTSPStatusRequest)(nil),       // 12: recognition.RTSPStatusRequest
	(*RTSPStatusResponse)(nil),      // 13: recognition.RTSPStatusResponse
	(*StartWorkerRequest)(nil),      // 14: recognition.StartWorkerRequest
	(*StartWorkerResponse)(nil),     // 15: recognition.StartWorkerResponse
	(*StopWorkerRequest)(nil),       // 16: recognition.StopWorkerRequest
	(*StopWorkerResponse)(nil),      // 17: recognition.StopWorkerResponse
	(*GetWorkerStatusRequest)(nil),  // 18: recognition.GetWorkerStatusRequest
	(*GetWorkerStatusResponse)(nil), // 19: recognition.GetWorkerStatusResponse
}
var file_recognition_proto_depIdxs = []int32{
	6,  // 0: recognition.TestRecognizeResponse.plates:type_name -> recognition.PlateResult
	7,  // 1: recognition.PlateResult.bounding_box:type_name -> recognition.BoundingBox
	0,  // 2: recognition.RecognitionService.HealthCheck:input_type -> recognition.Empty
	2,  // 3: recognition.RecognitionService.Ping:input_type -> recognition.PingRequest
	4,  // 4: recognition.RecognitionService.TestRecognize:input_type -> recognition.TestRecognizeRequest
	8,  // 5: recognition.RecognitionService.RecognizeFromRTSP:input_type -> recognition.RTSPRequest
	10, // 6: recognition.RecognitionService.StopRTSPRecognition:input_type -> recognition.StopRTSPRequest
	12, // 7: recognition.RecognitionService.GetRTSPStatus:input_type -> recognition.RTSPStatusRequest
	14, // 8: recognition.RecognitionService.StartWorker:input_type -> recognition.StartWorkerRequest
	16, // 9: recognition.RecognitionService.StopWorker:input_type -> recognition.StopWorkerRequest
	18, // 10: recognition.RecognitionService.GetWorkerStatus:input_type -> recognition.GetWorkerStatusRequest
	1,  // 11: recognition.RecognitionService.HealthCheck:output_type -> recognition.HealthResponse
	3,  // 12: recognition.RecognitionService.Ping:output_type -> recognition.PingResponse
	5,  // 13: recognition.RecognitionService.TestRecognize:output_type -> recognition.TestRecognizeResponse
	9,  // 14: recognition.RecognitionService.RecognizeFromRTSP:output_type -> recognition.RecognizeResponse
	11, // 15: recognition.RecognitionService.StopRTSPRecognition:output_type -> recognition.StopRTSPResponse
	13, // 16: recognition.RecognitionService.GetRTSPStatus:output_type -> recognition.RTSPStatusResponse
	15, // 17: recognition.RecognitionService.StartWorker:output_type -> recognition.StartWorkerResponse
	17, // 18: recognition.RecognitionService.StopWorker:output_type -> recognition.StopWorkerResponse
	19, // 19: recognition.RecognitionService.GetWorkerStatus:output_type -> recognition.GetWorkerStatusResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_recognition_proto_init() }
func file_recognition_proto_init() {
	if File_recognition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recognition_proto_rawDesc), len(file_recognition_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recognition_proto_goTypes,
		DependencyIndexes: file_recognition_proto_depIdxs,
		MessageInfos:      file_recognition_proto_msgTypes,
	}.Build()
	File_recognition_proto = out.File
	file_recognition_proto_goTypes = nil
	file_recognition_proto_depIdxs = nil
}
