// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: recognition.proto

package recognition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecognitionService_HealthCheck_FullMethodName         = "/recognition.RecognitionService/HealthCheck"
	RecognitionService_Ping_FullMethodName                = "/recognition.RecognitionService/Ping"
	RecognitionService_TestRecognize_FullMethodName       = "/recognition.RecognitionService/TestRecognize"
	RecognitionService_RecognizeFromRTSP_FullMethodName   = "/recognition.RecognitionService/RecognizeFromRTSP"
	RecognitionService_StopRTSPRecognition_FullMethodName = "/recognition.RecognitionService/StopRTSPRecognition"
	RecognitionService_GetRTSPStatus_FullMethodName       = "/recognition.RecognitionService/GetRTSPStatus"
)

// RecognitionServiceClient is the client API for RecognitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecognitionService provides automatic number plate recognition functionality
type RecognitionServiceClient interface {
	// Test methods
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	TestRecognize(ctx context.Context, in *TestRecognizeRequest, opts ...grpc.CallOption) (*TestRecognizeResponse, error)
	// Production methods
	RecognizeFromRTSP(ctx context.Context, in *RTSPRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	StopRTSPRecognition(ctx context.Context, in *StopRTSPRequest, opts ...grpc.CallOption) (*StopRTSPResponse, error)
	GetRTSPStatus(ctx context.Context, in *RTSPStatusRequest, opts ...grpc.CallOption) (*RTSPStatusResponse, error)
}

type recognitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecognitionServiceClient(cc grpc.ClientConnInterface) RecognitionServiceClient {
	return &recognitionServiceClient{cc}
}

func (c *recognitionServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RecognitionService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RecognitionService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) TestRecognize(ctx context.Context, in *TestRecognizeRequest, opts ...grpc.CallOption) (*TestRecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRecognizeResponse)
	err := c.cc.Invoke(ctx, RecognitionService_TestRecognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) RecognizeFromRTSP(ctx context.Context, in *RTSPRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, RecognitionService_RecognizeFromRTSP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) StopRTSPRecognition(ctx context.Context, in *StopRTSPRequest, opts ...grpc.CallOption) (*StopRTSPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRTSPResponse)
	err := c.cc.Invoke(ctx, RecognitionService_StopRTSPRecognition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recognitionServiceClient) GetRTSPStatus(ctx context.Context, in *RTSPStatusRequest, opts ...grpc.CallOption) (*RTSPStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RTSPStatusResponse)
	err := c.cc.Invoke(ctx, RecognitionService_GetRTSPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecognitionServiceServer is the server API for RecognitionService service.
// All implementations must embed UnimplementedRecognitionServiceServer
// for forward compatibility.
//
// RecognitionService provides automatic number plate recognition functionality
type RecognitionServiceServer interface {
	// Test methods
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	TestRecognize(context.Context, *TestRecognizeRequest) (*TestRecognizeResponse, error)
	// Production methods
	RecognizeFromRTSP(context.Context, *RTSPRequest) (*RecognizeResponse, error)
	StopRTSPRecognition(context.Context, *StopRTSPRequest) (*StopRTSPResponse, error)
	GetRTSPStatus(context.Context, *RTSPStatusRequest) (*RTSPStatusResponse, error)
	mustEmbedUnimplementedRecognitionServiceServer()
}

// UnimplementedRecognitionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecognitionServiceServer struct{}

func (UnimplementedRecognitionServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRecognitionServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRecognitionServiceServer) TestRecognize(context.Context, *TestRecognizeRequest) (*TestRecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRecognize not implemented")
}
func (UnimplementedRecognitionServiceServer) RecognizeFromRTSP(context.Context, *RTSPRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeFromRTSP not implemented")
}
func (UnimplementedRecognitionServiceServer) StopRTSPRecognition(context.Context, *StopRTSPRequest) (*StopRTSPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRTSPRecognition not implemented")
}
func (UnimplementedRecognitionServiceServer) GetRTSPStatus(context.Context, *RTSPStatusRequest) (*RTSPStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRTSPStatus not implemented")
}
func (UnimplementedRecognitionServiceServer) mustEmbedUnimplementedRecognitionServiceServer() {}
func (UnimplementedRecognitionServiceServer) testEmbeddedByValue()                            {}

// UnsafeRecognitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecognitionServiceServer will
// result in compilation errors.
type UnsafeRecognitionServiceServer interface {
	mustEmbedUnimplementedRecognitionServiceServer()
}

func RegisterRecognitionServiceServer(s grpc.ServiceRegistrar, srv RecognitionServiceServer) {
	// If the following call panics, it indicates UnimplementedRecognitionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecognitionService_ServiceDesc, srv)
}

func _RecognitionService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_TestRecognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).TestRecognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_TestRecognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).TestRecognize(ctx, req.(*TestRecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_RecognizeFromRTSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTSPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).RecognizeFromRTSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_RecognizeFromRTSP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).RecognizeFromRTSP(ctx, req.(*RTSPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_StopRTSPRecognition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRTSPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).StopRTSPRecognition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_StopRTSPRecognition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).StopRTSPRecognition(ctx, req.(*StopRTSPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecognitionService_GetRTSPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RTSPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecognitionServiceServer).GetRTSPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecognitionService_GetRTSPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecognitionServiceServer).GetRTSPStatus(ctx, req.(*RTSPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecognitionService_ServiceDesc is the grpc.ServiceDesc for RecognitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecognitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recognition.RecognitionService",
	HandlerType: (*RecognitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _RecognitionService_HealthCheck_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RecognitionService_Ping_Handler,
		},
		{
			MethodName: "TestRecognize",
			Handler:    _RecognitionService_TestRecognize_Handler,
		},
		{
			MethodName: "RecognizeFromRTSP",
			Handler:    _RecognitionService_RecognizeFromRTSP_Handler,
		},
		{
			MethodName: "StopRTSPRecognition",
			Handler:    _RecognitionService_StopRTSPRecognition_Handler,
		},
		{
			MethodName: "GetRTSPStatus",
			Handler:    _RecognitionService_GetRTSPStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recognition.proto",
}
