# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infrastructure.grpc.stubs import recognition_pb2 as recognition__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecognitionServiceStub(object):
    """RecognitionService provides automatic number plate recognition functionality
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/recognition.RecognitionService/HealthCheck',
                request_serializer=recognition__pb2.Empty.SerializeToString,
                response_deserializer=recognition__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/recognition.RecognitionService/Ping',
                request_serializer=recognition__pb2.PingRequest.SerializeToString,
                response_deserializer=recognition__pb2.PingResponse.FromString,
                _registered_method=True)
        self.TestRecognize = channel.unary_unary(
                '/recognition.RecognitionService/TestRecognize',
                request_serializer=recognition__pb2.TestRecognizeRequest.SerializeToString,
                response_deserializer=recognition__pb2.TestRecognizeResponse.FromString,
                _registered_method=True)
        self.TestRecognizeVideo = channel.unary_unary(
                '/recognition.RecognitionService/TestRecognizeVideo',
                request_serializer=recognition__pb2.TestVideoRequest.SerializeToString,
                response_deserializer=recognition__pb2.TestVideoResponse.FromString,
                _registered_method=True)
        self.RecognizeFromStream = channel.unary_unary(
                '/recognition.RecognitionService/RecognizeFromStream',
                request_serializer=recognition__pb2.StreamRequest.SerializeToString,
                response_deserializer=recognition__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.StopStreamRecognition = channel.unary_unary(
                '/recognition.RecognitionService/StopStreamRecognition',
                request_serializer=recognition__pb2.StopStreamRecognitionRequest.SerializeToString,
                response_deserializer=recognition__pb2.StopStreamRecognitionResponse.FromString,
                _registered_method=True)
        self.GetStreamRecognitionStatus = channel.unary_unary(
                '/recognition.RecognitionService/GetStreamRecognitionStatus',
                request_serializer=recognition__pb2.StreamRecognitionStatusRequest.SerializeToString,
                response_deserializer=recognition__pb2.StreamRecognitionStatusResponse.FromString,
                _registered_method=True)
        self.StartWorker = channel.unary_unary(
                '/recognition.RecognitionService/StartWorker',
                request_serializer=recognition__pb2.StartWorkerRequest.SerializeToString,
                response_deserializer=recognition__pb2.StartWorkerResponse.FromString,
                _registered_method=True)
        self.StopWorker = channel.unary_unary(
                '/recognition.RecognitionService/StopWorker',
                request_serializer=recognition__pb2.StopWorkerRequest.SerializeToString,
                response_deserializer=recognition__pb2.StopWorkerResponse.FromString,
                _registered_method=True)
        self.GetWorkerStatus = channel.unary_unary(
                '/recognition.RecognitionService/GetWorkerStatus',
                request_serializer=recognition__pb2.GetWorkerStatusRequest.SerializeToString,
                response_deserializer=recognition__pb2.GetWorkerStatusResponse.FromString,
                _registered_method=True)


class RecognitionServiceServicer(object):
    """RecognitionService provides automatic number plate recognition functionality
    """

    def HealthCheck(self, request, context):
        """Test methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRecognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRecognizeVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFromStream(self, request, context):
        """Production methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreamRecognition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamRecognitionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWorker(self, request, context):
        """Worker management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recognition__pb2.Empty.FromString,
                    response_serializer=recognition__pb2.HealthResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=recognition__pb2.PingRequest.FromString,
                    response_serializer=recognition__pb2.PingResponse.SerializeToString,
            ),
            'TestRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRecognize,
                    request_deserializer=recognition__pb2.TestRecognizeRequest.FromString,
                    response_serializer=recognition__pb2.TestRecognizeResponse.SerializeToString,
            ),
            'TestRecognizeVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRecognizeVideo,
                    request_deserializer=recognition__pb2.TestVideoRequest.FromString,
                    response_serializer=recognition__pb2.TestVideoResponse.SerializeToString,
            ),
            'RecognizeFromStream': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFromStream,
                    request_deserializer=recognition__pb2.StreamRequest.FromString,
                    response_serializer=recognition__pb2.RecognizeResponse.SerializeToString,
            ),
            'StopStreamRecognition': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreamRecognition,
                    request_deserializer=recognition__pb2.StopStreamRecognitionRequest.FromString,
                    response_serializer=recognition__pb2.StopStreamRecognitionResponse.SerializeToString,
            ),
            'GetStreamRecognitionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamRecognitionStatus,
                    request_deserializer=recognition__pb2.StreamRecognitionStatusRequest.FromString,
                    response_serializer=recognition__pb2.StreamRecognitionStatusResponse.SerializeToString,
            ),
            'StartWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorker,
                    request_deserializer=recognition__pb2.StartWorkerRequest.FromString,
                    response_serializer=recognition__pb2.StartWorkerResponse.SerializeToString,
            ),
            'StopWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWorker,
                    request_deserializer=recognition__pb2.StopWorkerRequest.FromString,
                    response_serializer=recognition__pb2.StopWorkerResponse.SerializeToString,
            ),
            'GetWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerStatus,
                    request_deserializer=recognition__pb2.GetWorkerStatusRequest.FromString,
                    response_serializer=recognition__pb2.GetWorkerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recognition.RecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recognition.RecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecognitionService(object):
    """RecognitionService provides automatic number plate recognition functionality
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/HealthCheck',
            recognition__pb2.Empty.SerializeToString,
            recognition__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/Ping',
            recognition__pb2.PingRequest.SerializeToString,
            recognition__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/TestRecognize',
            recognition__pb2.TestRecognizeRequest.SerializeToString,
            recognition__pb2.TestRecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRecognizeVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/TestRecognizeVideo',
            recognition__pb2.TestVideoRequest.SerializeToString,
            recognition__pb2.TestVideoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFromStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/RecognizeFromStream',
            recognition__pb2.StreamRequest.SerializeToString,
            recognition__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStreamRecognition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/StopStreamRecognition',
            recognition__pb2.StopStreamRecognitionRequest.SerializeToString,
            recognition__pb2.StopStreamRecognitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamRecognitionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/GetStreamRecognitionStatus',
            recognition__pb2.StreamRecognitionStatusRequest.SerializeToString,
            recognition__pb2.StreamRecognitionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/StartWorker',
            recognition__pb2.StartWorkerRequest.SerializeToString,
            recognition__pb2.StartWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/StopWorker',
            recognition__pb2.StopWorkerRequest.SerializeToString,
            recognition__pb2.StopWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recognition.RecognitionService/GetWorkerStatus',
            recognition__pb2.GetWorkerStatusRequest.SerializeToString,
            recognition__pb2.GetWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
