export { CamerasPage } from './cameras'
export { CameraPage } from './camera'
export { CameraAddPage } from './camera-add'
export { PlatesPage } from './plates'
export { AccessPointsPage } from './access-points'
export { HistoryPage } from './history'
export { TestRecognitionPage } from './test-recognition'
